name: habitat
description: Flutter App to help people trough college

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.2+7

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: 3.0.6
  typesense: ^0.2.0
  go_router: ^4.1.0
  cupertino_icons: ^1.0.2
  flutter_login: ^3.2.0
  firebase_core: ^1.14.0
  firebase_database: ^9.0.9
  firebase_auth: ^3.3.12
  cloud_firestore: ^3.1.11
  provider: ^6.0.2
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/
  fonts:    
    - family: League Gothic
      fonts:
        - asset: assets/League Gothic/LeagueGothic-Regular-VariableFont_wdth.ttf
  uses-material-design: true


